export const actionTypes = {
	SET_FIELD: 'SET_FIELD',
	SET_CURRENT_PLAYER: 'SET_CURRENT_PLAYER',
	SET_IS_GAME_ENDED: 'SET_IS_GAME_ENDED',
	SET_IS_DRAW: 'SET_IS_DRAW',
	RESTART_GAME: 'RESTART_GAME',
};
